
-- Definiera villkoren på tabeller 


-- Primärnycklar 

ALTER TABLE SHOP ADD CONSTRAINT SHOP_PK PRIMARY KEY (SHOPNO);

ALTER TABLE FILM ADD CONSTRAINT FILM_PK PRIMARY KEY (FNO);

ALTER TABLE EMP ADD CONSTRAINT EMP_PK PRIMARY KEY (EMPNO);

ALTER TABLE MEMB ADD CONSTRAINT MEMB_PK PRIMARY KEY (MEMBNO);

ALTER TABLE FILMSTAFF ADD CONSTRAINT STAFFNO_PK PRIMARY KEY (STAFFNO);

-- Primärnycklar till relationer mellan olika entitet

ALTER TABLE SHOP_HAS_FILM ADD CONSTRAINT SHOP_HAS_FILM_PK PRIMARY KEY (FNO, SHOPNO);

ALTER TABLE FILM_FILMSTAFF ADD CONSTRAINT FILM_FILMSTAFF_PK PRIMARY KEY (STAFFNO, FNO);

ALTER TABLE MEMB_RENT ADD CONSTRAINT MEMB_RENT_PK PRIMARY KEY (FNO, MEMBNO);

ALTER TABLE MEMB_RESERV ADD CONSTRAINT MEMB_RESERV_PK PRIMARY KEY (FNO, MEMBNO);





-- Främmande nycklar 



ALTER TABLE FILM ADD CONSTRAINT FILM_SHOP_FK FOREIGN KEY (SHOPNO) REFERENCES SHOP(SHOPNO) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE EMP ADD CONSTRAINT EMP_SHOP_FK FOREIGN KEY (SHOPNO) REFERENCES SHOP(SHOPNO) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE MEMB ADD CONSTRAINT MEMB_SHOP_FK FOREIGN KEY (SHOPNO) REFERENCES SHOP(SHOPNO) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE FILMSTAFF ADD CONSTRAINT FILMSTAFF_FILM_FK FOREIGN KEY (FNO) REFERENCES FILM(FNO) ON UPDATE CASCADE ON DELETE CASCADE;


-- Främmande nycklar till relationer mellan olika entitet

ALTER TABLE SHOP_HAS_FILM ADD CONSTRAINT SHOP_HAS_FILM_FILM_FK FOREIGN KEY (FNO) REFERENCES FILM(FNO) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE SHOP_HAS_FILM ADD CONSTRAINT SHOP_HAS_FILM_SHOP_FK FOREIGN KEY (SHOPNO) REFERENCES SHOP(SHOPNO) ON UPDATE CASCADE ON DELETE CASCADE;





ALTER TABLE FILM_FILMSTAFF ADD CONSTRAINT STAFF_FK FOREIGN KEY (STAFFNO) REFERENCES FILMSTAFF(STAFFNO) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE FILM_FILMSTAFF ADD CONSTRAINT FILM_FK FOREIGN KEY (FNO) REFERENCES FILM(FNO) ON UPDATE CASCADE ON DELETE CASCADE;





ALTER TABLE MEMB_RENT ADD CONSTRAINT MEMB_RENT_FILM_FK FOREIGN KEY (FNO) REFERENCES FILM(FNO) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE MEMB_RENT ADD CONSTRAINT MEMB_RENT_MEMB_FK FOREIGN KEY (MEMBNO) REFERENCES MEMB(MEMBNO) ON UPDATE CASCADE ON DELETE CASCADE;





ALTER TABLE MEMB_RESERV ADD CONSTRAINT MEMB_RESERV_FILM_FK FOREIGN KEY (FNO) REFERENCES FILM(FNO)  ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE MEMB_RESERV ADD CONSTRAINT MEMB_RESERV_MEMB_FK FOREIGN KEY (MEMBNO) REFERENCES MEMB(MEMBNO) ON UPDATE CASCADE ON DELETE CASCADE;



 
/*
 ON DELETE CASCADE   --Bra när du har svag-stark förhållande
 ON DELETE SET NULL  --Bra om du har en FK som inte har "NOT NULL" framför
 ON DELETE SET DEFAULT  --Bra om du har en FK som har ett default värde.
 
 */
 