/*
Detta är fler-radig kommentar!
 */
-- skapa tabellerna (detta en-radig kommentar)
CREATE TABLE SHOP
(
    SHOPNO      INTEGER     NOT NULL,
    SHOPNAME    VARCHAR(20),
    SHOPPHONE   INTEGER,
    SHOPGATE    VARCHAR(20),
    SHOPCITY    VARCHAR(20),
    SHOPHOUSENO INTEGER,
    SHOPPOSTNO  INTEGER
);

CREATE TABLE FILM
(
    FNO     INTEGER     NOT NULL,
    FTITLE  VARCHAR(20),
    FGENRE  VARCHAR(35),
    FLENGTH VARCHAR(11),
    SHOPNO  INTEGER     NOT NULL
);

CREATE TABLE EMP
(
    EMPNO  INTEGER     NOT NULL,
    ENAME  VARCHAR(20),
    EROLE  VARCHAR(11),
    ESAL   INTEGER,
    SHOPNO INTEGER     NOT NULL
);

CREATE TABLE MEMB
(
    MEMBNO      INTEGER     NOT NULL,
    MEMBNAME    VARCHAR(20),
    MEMBGATE    VARCHAR(20),
    MEMBCITY    VARCHAR(20),
    MEMBHOUSENO INTEGER,
    MEMBPOSTNO  INTEGER,
    SHOPNO      INTEGER     NOT NULL
);

CREATE TABLE FILMSTAFF
(
    STAFFNO   INTEGER     NOT NULL,
    STAFFNAME VARCHAR(20),
    FNO       INTEGER     NOT NULL
);


/*--------RELATIONER-----------*/
CREATE TABLE SHOP_HAS_FILM
(
    FNO    INTEGER     NOT NULL,
    SHOPNO INTEGER     NOT NULL,
    PRICE  INTEGER,
    COPIES INTEGER,
    STATUS BOOLEAN,
    SHELF  VARCHAR(10)
);
CREATE TABLE FILM_FILMSTAFF
(
    STAFFNO INTEGER     NOT NULL,
    FNO     INTEGER     NOT NULL,
    ROLL    VARCHAR(20)
);
CREATE TABLE MEMB_RENT
(
    FNO        INTEGER NOT NULL,
    MEMBNO     INTEGER NOT NULL,
    RENT_START DATE,
    RENT_END   DATE
);
CREATE TABLE MEMB_RESERV
(
    FNO          INTEGER NOT NULL,
    MEMBNO       INTEGER NOT NULL,
    RESERV_START DATE,
    RESERV_END   DATE
)