
DROP TABLE IF EXISTS SHOP CASCADE;   
DROP TABLE IF EXISTS FILM CASCADE;   
DROP TABLE IF EXISTS MEMB CASCADE;   
DROP TABLE IF EXISTS FILMSTAFF CASCADE;   
DROP TABLE IF EXISTS EMP CASCADE;   
DROP TABLE IF EXISTS SHOP_HAS_FILM CASCADE;
DROP TABLE IF EXISTS FILM_FILMSTAFF CASCADE;
DROP TABLE IF EXISTS MEMB_RENT CASCADE;
DROP TABLE IF EXISTS MEMB_RESERV CASCADE;
 
 